// export const ObjectImages = [
//     require('./cat.jpeg'),
//     require('./fish.jpeg'),
//     require('./hen.jpeg'),
//     require('./cow.jpeg'),
//     require('./pen.jpeg'),
//     require('./deer.jpeg'),
//     require('./orange.jpeg'),
//     require('./peacock.jpeg'),
//     require('./bus.jpeg'),
//     require('./helicopter.jpeg'),
//     require('./apple.jpeg'),
//     require('./car.jpeg'),
//     require('./cherry.jpeg'),
//     require('./pigion.jpeg'),
//     require('./tiger.jpeg'),
//     require('./banana.jpeg'),
//     require('./lion.jpeg'),
//     require('./penguin.jpeg'),
//     require('./duck.jpeg'),
//     require('./key.jpeg'),
//     require('./dog.jpeg'),
//     require('./owl.jpeg'),
//     require('./parrot.jpeg'),
//     require('./airplane.jpeg'),
//     require('./carrot.jpeg'),
//     require('./pencil.jpeg'),
//     require('./rabbit.jpeg'),
//     require('./horse.jpeg'),
//     require('./watermelon.jpeg'),
//     require('./potatto.jpeg'),
//     require('./cabbage.jpeg'),
//     require('./pinapple.jpeg'),
//     require('./ship.jpeg'),
//     require('./elephant.jpeg'),
//     require('./eagle.jpeg'),
//     require('./train.jpeg'),
//     require('./rat.jpeg'),
// ];




export const ObjectImages = [
    { key: 'cat', source: require('./cat.jpeg') },
    { key: 'fish', source: require('./fish.jpeg') },
    { key: 'hen', source: require('./hen.jpeg') },
    { key: 'cow', source: require('./cow.jpeg') },
    { key: 'pen', source: require('./pen.jpeg') },
    { key: 'deer', source: require('./deer.jpeg') },
    { key: 'orange', source: require('./orange.jpeg') },
    { key: 'peacock', source: require('./peacock.jpeg') },
    { key: 'bus', source: require('./bus.jpeg') },
    { key: 'helicopter', source: require('./helicopter.jpeg') },
    { key: 'apple', source: require('./apple.jpeg') },
    { key: 'car', source: require('./car.jpeg') },
    { key: 'cherry', source: require('./cherry.jpeg') },
    { key: 'pigeon', source: require('./pigion.jpeg') },
    { key: 'tiger', source: require('./tiger.jpeg') },
    { key: 'banana', source: require('./banana.jpeg') },
    { key: 'lion', source: require('./lion.jpeg') },
    { key: 'penguin', source: require('./penguin.jpeg') },
    { key: 'duck', source: require('./duck.jpeg') },
    { key: 'key', source: require('./key.jpeg') },
    { key: 'dog', source: require('./dog.jpeg') },
    { key: 'owl', source: require('./owl.jpeg') },
    { key: 'parrot', source: require('./parrot.jpeg') },
    { key: 'airplane', source: require('./airplane.jpeg') },
    { key: 'carrot', source: require('./carrot.jpeg') },
    { key: 'pencil', source: require('./pencil.jpeg') },
    { key: 'rabbit', source: require('./rabbit.jpeg') },
    { key: 'horse', source: require('./horse.jpeg') },
    { key: 'watermelon', source: require('./watermelon.jpeg') },
    { key: 'potato', source: require('./potatto.jpeg') },
    { key: 'cabbage', source: require('./cabbage.jpeg') },
    { key: 'pineapple', source: require('./pinapple.jpeg') },
    { key: 'ship', source: require('./ship.jpeg') },
    { key: 'elephant', source: require('./elephant.jpeg') },
    { key: 'eagle', source: require('./eagle.jpeg') },
    { key: 'train', source: require('./train.jpeg') },
    { key: 'rat', source: require('./rat.jpeg') },
];
